# Generated by Django 4.0.3 on 2022-12-08 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales_rest', '0002_rename_salerecord_salesrecord'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SalesRecord',
            new_name='SaleRecord',
        ),
        migrations.AlterField(
            model_name='salesrep',
            name='employee_id',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
